---
apiVersion: v1
kind: Service
metadata:
  name: sprinpetclininc-deployment
  labels:
    app: petclinic
spec:
  ports:
    - port: 8080
  selector:
    app: petclinic
  type: LoadBalancer
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: petclinic-deploy
  labels:
    app: petclinic
spec:
  replicas: 5
  selector:
    matchLabels:
      app: petclinic
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 25%
      maxSurge: 1
  template:
    metadata:
      labels:
        app: petclinic
    spec:
      containers:
        - image: abhish9416/spc:latest
          name: petclinic
          env:
            - name: MYSQL_SERVER
              value: mysql-svc
          ports:
            - containerPort: 8080
              name: flaskport

